tuple=('c','c++','java','python','html','css','react.js')
print(tuple)
print(type(tuple))
print("=======================================================")
print("accessing using positive indexing")
print(tuple[0])
print(tuple[1])
print(tuple[2])
print(tuple[3])
print(tuple[4])
print(tuple[5])
print(tuple[6])
print("accessing using negative indexing")
print(tuple[-7])
print(tuple[-6])
print(tuple[-5])
print(tuple[-4])
print(tuple[-3])
print(tuple[-2])
print(tuple[-1])
